import { Property } from "./types";

export const properties: Property[] = [
  {
    id: "1",
    title: "Luxury Villa with Pool",
    type: "Villa",
    listing: "For Sale",
    price: 450000,
    priceUnit: "USD",
    location: "Nyarutarama, Kigali",
    district: "Gasabo",
    bedrooms: 5,
    bathrooms: 4,
    area: 420,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=80",
    ],
    description:
      "An exceptional luxury villa nestled in the prestigious Nyarutarama neighborhood. This stunning property features an open-plan living area, a gourmet kitchen, a private swimming pool, and manicured gardens. Built with premium finishes throughout, it offers an unparalleled lifestyle for discerning buyers.",
    features: ["Swimming Pool", "Garden", "Security", "Parking", "Generator", "Solar Panels", "Borehole"],
    featured: true,
  },
  {
    id: "2",
    title: "Modern 3BR Apartment",
    type: "Apartment",
    listing: "For Rent",
    price: 1500,
    priceUnit: "USD",
    period: "month",
    location: "Kiyovu, Kigali",
    district: "Nyarugenge",
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80",
    ],
    description:
      "A stunning modern apartment in the heart of Kiyovu. This fully furnished unit boasts panoramic city views, contemporary design, and top-of-the-line appliances. Perfect for professionals and expats seeking comfort and convenience in Kigali's prime district.",
    features: ["City View", "Gym", "24/7 Security", "Parking", "Backup Power", "High-Speed Internet"],
    featured: true,
  },
  {
    id: "3",
    title: "Family Home with Garden",
    type: "House",
    listing: "For Sale",
    price: 185000,
    priceUnit: "USD",
    location: "Remera, Kigali",
    district: "Gasabo",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80",
    ],
    description:
      "A beautiful family home located in the quiet residential area of Remera. Featuring spacious rooms, a lush private garden, and a double garage. Close to international schools, supermarkets, and the airport. Ideal for families looking for a safe and comfortable environment.",
    features: ["Garden", "Double Garage", "Security Wall", "Parking", "Staff Quarters", "Borehole"],
    featured: true,
  },
  {
    id: "4",
    title: "Studio Apartment – City Center",
    type: "Apartment",
    listing: "For Rent",
    price: 800,
    priceUnit: "USD",
    period: "month",
    location: "Kimihurura, Kigali",
    district: "Gasabo",
    bedrooms: 1,
    bathrooms: 1,
    area: 60,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=80",
    ],
    description:
      "A cozy and well-designed studio apartment in the vibrant Kimihurura area. Fully furnished with modern appliances, the unit is ideal for single professionals or couples. Walking distance to top restaurants, embassies, and the Kigali Convention Center.",
    features: ["Furnished", "High-Speed Internet", "Security", "Parking", "Backup Power"],
    featured: false,
  },
  {
    id: "5",
    title: "Modern Townhouse",
    type: "Duplex",
    listing: "For Sale",
    price: 220000,
    priceUnit: "USD",
    location: "Gisozi, Kigali",
    district: "Gasabo",
    bedrooms: 4,
    bathrooms: 3,
    area: 310,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
    ],
    description:
      "A contemporary townhouse in the rapidly developing Gisozi district. Spread over two floors, it features an open-plan kitchen, a rooftop terrace with hill views, and a private courtyard. An excellent investment in one of Kigali's most sought-after neighborhoods.",
    features: ["Rooftop Terrace", "Courtyard", "Security", "Parking", "Hill View"],
    featured: true,
  },
  {
    id: "6",
    title: "Penthouse with Panoramic View",
    type: "Apartment",
    listing: "For Rent",
    price: 2500,
    priceUnit: "USD",
    period: "month",
    location: "Kiyovu, Kigali",
    district: "Nyarugenge",
    bedrooms: 3,
    bathrooms: 3,
    area: 220,
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=80",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    ],
    description:
      "The crown jewel of Kigali luxury rentals. This top-floor penthouse offers sweeping panoramic views of the city and the Nyandungu wetlands. Featuring floor-to-ceiling windows, a private terrace, smart home technology, and premium designer furnishings.",
    features: ["Panoramic View", "Private Terrace", "Smart Home", "Gym Access", "Concierge", "Underground Parking"],
    featured: true,
  },
  {
    id: "7",
    title: "Executive Villa – Diplomatic Zone",
    type: "Villa",
    listing: "For Sale",
    price: 380000,
    priceUnit: "USD",
    location: "Kimihurura, Kigali",
    district: "Gasabo",
    bedrooms: 6,
    bathrooms: 5,
    area: 500,
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
    ],
    description:
      "A grand executive villa in Kigali's prestigious diplomatic zone. This gated estate sits on a half-acre plot and features a guest house, a swimming pool, multiple entertainment areas, and lush tropical gardens. Ideal for ambassadors, executives, and high-net-worth families.",
    features: ["Guest House", "Swimming Pool", "Garden", "Gate House", "Generator", "Staff Quarters", "Solar"],
    featured: false,
  },
  {
    id: "8",
    title: "3BR Apartment – Kibagabaga",
    type: "Apartment",
    listing: "For Rent",
    price: 1200,
    priceUnit: "USD",
    period: "month",
    location: "Kibagabaga, Kigali",
    district: "Gasabo",
    bedrooms: 3,
    bathrooms: 2,
    area: 145,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
    ],
    description:
      "A spacious and modern apartment in the tranquil Kibagabaga neighbourhood. Offering generous room sizes, quality finishes, a balcony with garden views, and secure underground parking. Close to supermarkets, restaurants, and major road networks.",
    features: ["Balcony", "Parking", "Security", "Generator", "Internet Ready"],
    featured: false,
  },
  {
    id: "9",
    title: "Starter Home – Gikondo",
    type: "House",
    listing: "For Sale",
    price: 150000,
    priceUnit: "USD",
    location: "Gikondo, Kigali",
    district: "Kicukiro",
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80",
    ],
    description:
      "An affordable and well-maintained family home in the up-and-coming Gikondo district. Perfect as a starter home or investment property. Features a bright living area, modern kitchen, a courtyard, and convenient access to Kigali's main roads.",
    features: ["Courtyard", "Security Wall", "Parking", "Modern Kitchen"],
    featured: false,
  },
  {
    id: "10",
    title: "Luxury Duplex – Nyarutarama",
    type: "Duplex",
    listing: "For Sale",
    price: 320000,
    priceUnit: "USD",
    location: "Nyarutarama, Kigali",
    district: "Gasabo",
    bedrooms: 5,
    bathrooms: 4,
    area: 380,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80",
    ],
    description:
      "A sophisticated luxury duplex in the leafy Nyarutarama neighbourhood. The property features a beautiful lake-view terrace, a home office, a cinema room, and a private gym. Designed by one of Rwanda's top architects, this is truly a statement property.",
    features: ["Lake View", "Home Office", "Cinema Room", "Private Gym", "Security", "Parking"],
    featured: true,
  },
  {
    id: "11",
    title: "Studio – Remera",
    type: "Apartment",
    listing: "For Rent",
    price: 650,
    priceUnit: "USD",
    period: "month",
    location: "Remera, Kigali",
    district: "Gasabo",
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=80",
    ],
    description:
      "A compact and stylish studio apartment in Remera, close to Kigali International Airport. Ideal for business travellers and short-to-mid-term stays. Comes furnished with modern appliances, fast internet, and 24/7 security.",
    features: ["Furnished", "Near Airport", "Security", "Internet", "Parking"],
    featured: false,
  },
  {
    id: "12",
    title: "Hillside Home – Kanombe",
    type: "House",
    listing: "For Sale",
    price: 200000,
    priceUnit: "USD",
    location: "Kanombe, Kigali",
    district: "Kicukiro",
    bedrooms: 4,
    bathrooms: 3,
    area: 260,
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&q=80",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80",
    ],
    description:
      "A charming hillside home in Kanombe with breathtaking views of Kigali's rolling hills. Featuring a wraparound veranda, an outdoor dining area, a lush garden, and a borehole. A serene escape while remaining just minutes from the city centre.",
    features: ["Hill View", "Veranda", "Garden", "Borehole", "Security", "Parking"],
    featured: false,
  },
];

export const getFeatured = () => properties.filter((p) => p.featured);
export const getById = (id: string) => properties.find((p) => p.id === id);
